### ISSUE TITLE
Optional secondary label

### ISSUE THREAD

**Issue by alallier** [kethinov/semanticforms#24]
I'd love to have a discussion to what a good UI pattern would look like to display the accepted pattern in a form element.

We could try and fit it next to the floating label assuming the label wasn't too long.

**Comment by kethinov** [comment]
This is kind of what the placeholder attribute is for. To give the user hints about what an acceptable input would look like. For example, in the email form the placeholder reads "e.g. john.smith@somewhere.com" which is like a human-readable version of the regex pattern that the field will accept.

In terms of actually exposing the regex pattern visually in the (probably quite rare) case that would be desirable on top of having a human-readable placeholder, it might be possible to add a feature which displays it in the top right corner of the form when it's focused (or only when focused + is errored out), similar to how the label moves up to the top left.

**Comment by alallier** [comment]
I'm not talking about exposing the cryptic regex pattern but rather assisting the user in remembering a more complex human-readable placeholder.

This is what I had in mind when filing the issue originally. Since the HTML date/time input element really sucks and can't support alternative date/time formats I have to end up using the regular text input to take in the date string I want. That date string is `dd/HHmm Z MMM YYYY`. I provide that as placeholder but as soon as you type the first number into the input box it can be easy to forgot what human readable format the input box is looking for.

**Comment by kethinov** [comment]
Proposed solution:

What we have today:

```html
<form class='semanticForms'>
  <dl>
    <dt><label for='name'>Name</label></dt>
    <dd><input id='name' name='name' type='text' placeholder='e.g. John Smith'></dd>
  </dl>
</form>
```

We could enhance this like so:

```html
<form class='semanticForms'>
  <dl>
    <dt><label for='name'>Name</label> <label for='name'>(first and last name required)</label></dt>
    <dd><input id='name' name='name' type='text' placeholder='e.g. John Smith'></dd>
  </dl>
</form>
```

The second label would display beside the first in a non-JS scenario. In the JS scenario, we could program the JS to make a second label (if present) appear right-aligned above the form in smaller text, floating up to the right corner similar to how the first label floats up to the left corner.
