### ISSUE TITLE
checkbox error

### ISSUE THREAD

**Issue by peterbsmith2** [kethinov/semanticforms#4]
Given:
```html
<form id="" action='/somewhere' method='post' class='semanticForms' data-clearfield-horizontal-offset='25' data-clearfield-vertical-offset='5'>
  <fieldset>
    <dl>
      <dt>
        <label for='statusReportedInput'>Status Reported</label>
      </dt>
      <dd>
        <input id='statusReportedInput' name='statusReportedInput' type='checkbox'>
      </dd>
    </dl>
    <input type='submit' name='submit' id='save' value='Save'>
    <input type='submit' name='cancel' id='cancel' value='Cancel'>
  </fieldset>
</form>
```
The following error is produced: 
`
DOMException: Failed to execute 'querySelector' on 'Document': 'label[data-for=]' is not a valid selector.
`

Originating from [line 59 of semanticforms.js](https://github.com/kethinov/semanticforms/blame/master/semanticForms.js#L51)

**Comment by kethinov** [comment]
Need a class of `checkboxes` on the `<dd>`.

See example: https://kethinov.github.io/semanticforms/semanticForms.html

**Comment by kethinov** [comment]
Reopen if you still have questions.
