### ISSUE TITLE
input type="image" not fully handled yet

### ISSUE THREAD

**Issue by kethinov** [kethinov/semanticforms#50]
Needs more CSS love and attention.

**Comment by kethinov** [comment]
Sure, go for it! General info on how to hack the code and do a build is at the bottom of the [README](https://github.com/kethinov/semanticforms).

To get started to see the problem, try changing [this line](https://github.com/kethinov/semanticforms/blob/b09603fe4f9201005867ba987fd9ccc8125c5159/semanticForms.html#L126) to:

`<li><input type="image" name="image" value="Button 2"></li>`

Then I think you'll see what I mean about it not looking very good yet. There isn't much code in this repo to handle `input[type="image"]` yet.

More info about `input[type="image"]` [here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/image).

**Comment by ijklmopffs** [comment]
Alright, will get on it
