### ISSUE TITLE
Need styling support for required attribute

### ISSUE THREAD

**Issue by kethinov** [kethinov/semanticforms#54]
Should turn fields red.

**Comment by masoudhsd** [comment]
Hello, I have a question.
which fields are required?

**Comment by kethinov** [comment]
This refers to adding the `required` attribute to any forms styled by this library. For example, alter [this page](https://kethinov.github.io/semanticforms/semanticForms.html), add the `required` attribute to one of the fields, and attempt to submit the form without filling in any info.
